### ISSUE TITLE
Remove `www` from `https://www.omim.org/phenotypicSeries/PS`

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/omim#103]
## Overview
This would likely involve some changes in `mondo-ingest` and `mondo` as well I would imagine.

## Sub-tasks
- [x] 1. Fix in `omim` repo https://github.com/monarch-initiative/omim/pull/107#pullrequestreview-1953659980
- [x] 2. Fix in `mondo-ingest` repo https://github.com/monarch-initiative/mondo-ingest/pull/478
  - [x] `config/prefixes.csv`
  - [x] `metadata/omim.yml`
  - [x] Do a broad find/replace of `https://www.omim.org/phenotypicSeries/PS` to `https://omim.org/phenotypicSeries/PS`, as there are other metadata files with prefix maps with OMIMPS refs, and other refs elsewhere as well

**Comment by matentzn** [comment]
How did this arise? There should be one way and one way only to describe phenotypic series IRIs, and that's defined in Mondo ingest prefix map!

**Comment by matentzn** [comment]
This need to correspond to whatever you have in omim.owl

**Comment by joeflack4** [comment]
Not sure. The OMIM ingest predates a short time before I started working for BIDS at JHU. It's probably been this way long before I found out about the `mondo-ingest` `prefix_map`.

**Comment by matentzn** [comment]
I mean, just look in omim.owl how OMIMPS Uris are written!

**Comment by joeflack4** [comment]
Sorry, when I said "not sure", I was not responding to "This need to correspond to whatever you have in omim.owl". I edited my comment to clarify.

It sounds like what you are saying is that, going forward for the `omim` repository, the OMIPS URI stem should match what we have currently in `mondo-ingest` `components/omim.owl`. If I'm wrong please correct.

I did look at `components/omim.owl`, and I see it's using:
```owl
        <rdfs:subClassOf rdf:resource="https://www.omim.org/phenotypicSeries/PS100070"/>
```
In the `omim` repo's `omim.ttl`, its:
```ttl
@prefix OMIMPS: <https://www.omim.org/phenotypicSeries/PS> .
```

So they currently match.

But the `www` is still in there, which sounds like it's a problem.

---

I'm not sure in in `mondo-ingest` what the most authoritative are for prefix maps is I'm assuming it's in each `metadata/ONTOLOGY.yml`. And I'm assuming we eventually want `config/prefixes.csv` to be dynamically generated from those if it's not already. For `omim.yml` we have: `OMIMPS: https://omim.org/phenotypicSeries/PS`. 

---

In any case, it's unclear to me currently whether i should proceed forward with fixing the OMIMPS URI stem to remove the `www` in the `omim` repository, or any other action items needed. And should I consider this a low/medium priority? @matentzn Please advise.

**Comment by matentzn** [comment]
A URI mismatch is generally a very high-priority issue. But, right now, everything works fine (the pipeline works):

https://github.com/monarch-initiative/mondo-ingest/blob/main/src/ontology/slurp/omim.tsv#L64

Right now, I care only about the fact that the whole system runs; so lets keep this issue open, but as low-priority. If someone external puts pressure on us to change the OMIMPS URIs we will do immediately.

**Comment by joeflack4** [comment]
Subtask (1), the OMIM side, was handled by https://github.com/monarch-initiative/omim/pull/107#pullrequestreview-1953659980. I remember this coming up. I thought I added a review comment about it connecting to this. Either my memory serves incorrectly, or we failed to follow up. In any case, subtask (2), the `mondo-ingest` side, was handled today by https://github.com/monarch-initiative/mondo-ingest/pull/478.

**Comment by matentzn** [comment]
As I am really deeply afraid of this change, I would like to suggest:

1. To make a OMIM release locally and stick it on dropbox
2. Create a mondo ingest branch and update mondo-ingest-odk.yaml with the link to that omim release
3. Run make `update_import`
4. Make draft PR and assign to Trish for review
5. Run whole release pipeline on that branch
6. Make another draft PR with the data updates and assign to Trish for review, with a special emphasis on changes to OMIM related data files (I should also review that).

**Comment by joeflack4** [comment]
@matentzn You already implemented this change on the `omim` side in [#107](https://github.com/monarch-initiative/omim/pull/107#pullrequestreview-1953659980), and it did have downstream effects on the `mondo-ingest` side that were fixed in https://github.com/monarch-initiative/mondo-ingest/pull/478.

Of course, there might be more effects that we haven't noticed yet. However as everything is merged already, we might as well review the state of things as they are now in production.
