### ISSUE TITLE
NCBITaxon:9606 is missing prefix

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/omim#11]
## Edits
1. Added task list, header for "individual sub-issues", and numbered the headers under that - _joeflack4 2021/12/20_

## Task list
- [x] 1. Wrong IRI NCBITaxon:9606
- [x] 2. Labels should be totally lowercase, unless first word in "name" dictionary
  - [x] 2a. lowercase
  - [x] 2b. "name" dict replacements
- [x] 3. Obsolete terms have no labels?
- [x] 4. Genes use abbreviations as main labels?

### 1. Wrong IRI NCBITaxon:9606

```
<NCBITaxon:9606> a owl:Class ;
    rdfs:label "Homo sapiens" .
```

should be 

```
NCBITaxon:9606 a owl:Class ;
    rdfs:label "Homo sapiens" .
```
### 2. Labels should be totally lowercase, unless first word in "name" dictionary

```
OMIM:100050 a owl:Class ;
    rdfs:label "Aarskog Syndrome, Autosomal Dominant" ;
    IAO:0000142 PMID:6344635,
        PMID:6652957 ;
    oboInOwl:hasDbXref UMLS:C3149220 ;
    oboInOwl:hasExactSynonym "aarskog syndrome, autosomal dominant" .
```

should be 

```
OMIM:100050 a owl:Class ;
    rdfs:label "Aarskog syndrome, autosomal dominant" ;
    IAO:0000142 PMID:6344635,
        PMID:6652957 ;
    oboInOwl:hasDbXref UMLS:C3149220 ;
    oboInOwl:hasExactSynonym "Aarskog syndrome, autosomal dominant".
```

Note that for the first pass, you don't need to recognise Aarskog to be a name (what a name), so everything will probably simply be lowercase, i.e. `aarskog syndrome, autosomal dominant`.

 Similarly, this:

```
OMIM:100200 a owl:Class ;
    rdfs:label "Abducens Palsy" ;
    oboInOwl:hasDbXref UMLS:C4551519 ;
    oboInOwl:hasExactSynonym "abducens palsy" .
```

should be:

```
OMIM:100200 a owl:Class ;
    rdfs:label "abducens palsy" ;
    oboInOwl:hasDbXref UMLS:C4551519 ;
    oboInOwl:hasExactSynonym "abducens palsy" .
```

### 3. Obsolete terms have no labels?

```
OMIM:100500 a owl:Class ;
    IAO:0100001 OMIM:200150 ;
    owl:deprecated true .
```

Any way we can get these to have labels, and perhaps even biolink categories?

### 4. Genes use abbreviations as main labels?

That is probably a good idea, but should be discussed at the next meeting.

**Comment by matentzn** [comment]
NCBITaxon:9606 still missing prefix, see above

**Comment by joeflack4** [comment]
@matentzn While I have put in a fix for (3), it is only one of several possible solutions, and I need some input as to if I need to make any further updates.

The chief issue here is that, at least w/ the data I have, any obsolete/deprecated classes do not list any labels. What they do list are IDs for 0 to 2+ IDs to any MIM#s that they have been replaced by. So in the case of 0, there will be no label, still. Is that OK? In the case of 1, the labels are now added (as well as all other info I can glean, if that's desirable). In the case of 2+ labels, all labels & other info have been added. However, I have noticed that these labels can be highly disparate. They look like either (a) different diseases, or (b) very different aspects of the same/similar disease.

## Example screenshots
### For obsolete classes, where in normal cases, there would be labels displayed here, instead is other information.
<img width="466" alt="obsolescence reasons" src="https://user-images.githubusercontent.com/13045020/146866627-adf39c6b-554e-4c35-ae26-4206c5384e74.png">

### Example of a case of disparate labels
#### Entry was "moved" to multiple new entries
<img width="473" alt="replaced obsolete mim entries have disparate labels - 1" src="https://user-images.githubusercontent.com/13045020/146866700-f6559946-bbfc-4c75-9822-42c87c34e5a6.png">

#### Labels for 1st referenced entry
<img width="477" alt="replaced obsolete mim entries have disparate labels - 2" src="https://user-images.githubusercontent.com/13045020/146866758-cc901195-603b-47b3-92b5-f0ad312e2436.png">

#### Labels for 2nd referenced entry
<img width="470" alt="replaced obsolete mim entries have disparate labels - 3" src="https://user-images.githubusercontent.com/13045020/146866765-6361cc08-5a91-4066-abe6-d1267c2b96e9.png">

**Comment by joeflack4** [comment]
@matentzn For (4), yes, that is the case. This is how Dazhi wrote it. If you want me to change, I can do that. But as you mentioned, this is something we can discuss at a meeting.

**Comment by matentzn** [comment]
- Lets leave (4), genes as abbrevi. as is for now. 
- Lets drop (3) - no labels on deprecated classes. I think this could turn out to be very confusing. Thanks for checking!

**Comment by joeflack4** [comment]
@matentzn Thanks for the response! (3) required a fair amount of refactoring to implement, but I hear you. It should take but a few minutes to deactivate this.

**Comment by matentzn** [comment]
Maybe I misunderstood - I thought the result was a bit ambiguous? My feeling is that unless we can reliably identify the label just before the obsoletion, we should probably not add it. What do you think? How confident are you about these labels? If you are 90, 95% confident I am happy to keep what you have!

**Comment by joeflack4** [comment]
From what I've seen, I'm >50% confident that these labels, in many/most cases, are _not_ representative of the term that was deprecated. But there is ambiguity. If you want to take the time or delegate to someone to look over these (someone who is more knowledgeable about medical terminology than I), let me know, and I can add a configuration option to the build to generate additional triples for deprecated terms.

Note that not only can/will you get labels for any terms the MIM entry was marked "moved to", but you'll also get other information all other available information about those terms. At least, that's the way it was set up; it was easier that way.
