### ISSUE TITLE
Bug: Symbols not always uppercase

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/omim#126]
## Overview
In working on #119, I noticed that some of the the `mondo#abbreviation` we're adding (these are actually _symbols_) are lowercase.

This is not expected. `mondo#abbreviation`s should all be uppercase.
And also I would expect that symbols always be uppercase too, as I learned from Trish. And a [cursory search](https://en.wikipedia.org/wiki/Gene_nomenclature#Human) seems to corroborate that.

The source of this bug in the code appears to be [`cleanup_label()`](https://github.com/monarch-initiative/omim/blob/dc3c79a5606a495cd7a08623ed4ac17c234d0575/omim2obo/parsers/omim_entry_parser.py#L168) and [`_detect_abbreviations()`](https://github.com/monarch-initiative/omim/blob/dc3c79a5606a495cd7a08623ed4ac17c234d0575/omim2obo/parsers/omim_entry_parser.py#L125).

I think it could be that (a) there's bugs in these functions, or (b) these functions simply should not be applied to symbols--at least not the ones on "Preferred title; symbol", and are only supposed to be used on other labels or parts of labels.

## Examples
[OMIM:126370](https://omim.org/entry/126370) - _hs3_
```ttl
OMIM:126370 a owl:Class ;
    rdfs:label "dna, satellite, 3" ;
    MONDO:exclusionReason MONDO:excludeTrait ;
    oboInOwl:hasExactSynonym "D1Z1",
        "dna, satellite, 3",
        "hs3" .
```

## Sub-tasks
- [ ] 1. Fix any related bugs
  - [ ] Could this bug be because the parser is expecting only 1 symbol, but this one has 2 symbols?
- [ ] 2. Refactor?: Should we just capitalize all symbols, rather than change casing based on logic in `cleanup_label()`?

**Comment by twhetzel** [comment]
@joeflack4 the original content from OMIM should be parsed so that what is labeled as a symbol by OMIM becomes tagged as an abbreviation in the omim.owl file that is created. The capitalization here does not matter.

**Comment by joeflack4** [comment]
I'm fairly confident that this is a bug in the code, based on what I've seen in just logically. I think I know where it is. And it may only happen when there are multiple symbols. 

But I think it does matter, because this will make its way into mondo. We will have things that are marked as abbreviations otherwise do not pass our normal criteria. That is, it will be lowercase. 

Unless I am misunderstanding the importance of this criteria. Is it important that we have it consistent? That we make sure that 100% of our synonyms marked as abbreviations are indeed uppercase, etc?

If that's not important, then we can close this issue.

If we do want to reach 100%, some of this can be dealt with by making sure the pipelines are correct, but I'm sure some of this will be on the curation side as well, assuming there are currently some synonyms in Mondo already that have this problem.

**Comment by joeflack4** [comment]
That sounds correct to me as well.

I'll add this bug fix then to #128 or I can make a separate PR for that first if you want.

**Comment by joeflack4** [comment]
resolved by #130
