### ISSUE TITLE
Slurp: Deprecation updates

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/omim#87]
## Overview
There are some obsolete/deprecated OMIM terms that made their way into Mondo. Perhaps there is still some work to be done on the slurp?

## Sub-task list
- [x] 1. Figure out how to identify deprecated terms in OMIM, if not already
- [x] 2. Make sure they are labeled as such in the output
- [ ] 3. Make sure this information is slurped: We basically need (i) a list of all deprecated OMIM terms for now, and (ii) their replacement if any

## Related
- https://github.com/monarch-initiative/mondo/issues/5640
- https://github.com/monarch-initiative/mondo-ingest/issues/74
- https://github.com/monarch-initiative/mondo-ingest/issues/116

**Comment by matentzn** [comment]
This issue was great! Leave it! Forget what I said on slack.

**Comment by joeflack4** [comment]
Looks like the OMIM ingest side of things is done. Example: 
```owl
OMIM:102590 a owl:Class ;
    IAO:0100001 OMIM:614413 ;
    owl:deprecated true .
```

How it's identified (`mimTitles.txt`):
```tsv
Prefix	MIM Number	Preferred Title; symbol	Alternative Title(s); symbol(s)	Included Title(s); symbols
Caret	102640	MOVED TO 102630
```

**Comment by matentzn** [comment]
Excellent. The sync will be easy p easy for you then. Unfortunately we don't meet tomorrow, but if you can prepare a robot template with the MONDO ID in one column, obsolete OMIM id in one column and a string saying "MONDO:equivalentObsolete" in a third, we can hash out the rest on Friday.

**Comment by joeflack4** [comment]
I located 91 mapped deprecated terms in Mondo out of 1,345 deprecated OMIM terms.

Analysis and outputs in PR: https://github.com/monarch-initiative/mondo-ingest/pull/108
